### ISSUE TITLE
2D classification fails

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#100]
> Thu Sep 13 18:10:12 PDT 2018 > QUEUE : SUCCESS : NGBW-JOB-RELION_2D_CLASS_COMET-8E3A2AB54E784547B17F37C2D766B7E6 : Added to run queue. 
> Thu Sep 13 18:10:15 PDT 2018 > INPUTSTAGING : SUCCESS : NGBW-JOB-RELION_2D_CLASS_COMET-8E3A2AB54E784547B17F37C2D766B7E6 : Staging input files to COMET 
> Thu Sep 13 18:10:15 PDT 2018 > INPUTSTAGING : SUCCESS : NGBW-JOB-RELION_2D_CLASS_COMET-8E3A2AB54E784547B17F37C2D766B7E6 : Input files staged successfully 
> Thu Sep 13 18:10:24 PDT 2018 > SUBMITTING : ERROR : NGBW-JOB-RELION_2D_CLASS_COMET-8E3A2AB54E784547B17F37C2D766B7E6 : java.lang.Exception: Error submitting job: /projects/cosmic2/gateway/workspace/NGBW-JOB-RELION_2D_CLASS_COMET-8E3A2AB54E784547B17F37C2D766B7E6 . Traceback (most recent call last): File "/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/comet_relion_submit.py", line 318, in <module> relion_command,outdir,runhours,nodes,numiters=prepareRelionRun(args['commandline']) File "/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/comet_relion_submit.py", line 46, in prepareRelionRun starfiledirname=rln_line.split()[colnum].split('@')[-1].split('/') IndexError: list index out of range

**Comment by mcianfrocco** [comment]
Fixed problem (due to handling of star file info). New problem: 

Reformatted star files are missing particle info: 

Original file - 
/projects/cosmic2/gateway/workspace/ARCHIVE/NGBW-JOB-RELION_2D_CLASS_COMET-CC0250E9CCDE427B8B6A565187FE9E0C/Extract/job080/particles.star 

New file - 
/projects/cosmic2/gateway/workspace/ARCHIVE/NGBW-JOB-RELION_2D_CLASS_COMET-CC0250E9CCDE427B8B6A565187FE9E0C/Extract/job080/particles_cosmic_path_updated.star

**Comment by mcianfrocco** [comment]
Related to #112 - relative paths aren't read correctly at this moment
