### ISSUE TITLE
Error messages output path information

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#122]
I think for security, we should NOT show full path in our user-facing messages.

Currently, this is happening in error output in 2 places:

1. Job completion email sent to the user currently says 

> Error submitting job: Error submitting job: /projects/cosmic2/gateway/workspace/NGBW-JOB-RELION_2D_CLASS_COMET-2EAFA1772CC148C382E2A222890D741F . Traceback (most recent call last): File "/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/comet_relion_submit.py", line 349, in relion_command,outdir,runhours,nodes,numiters,worksubdir=prepareRelionRun(args['commandline']) File "/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/comet_relion_submit.py", line 50, in prepareRelionRun rlno1=open(starfilename,'r') IOError: [Errno 2] No such file or directory: 'data/2d'

2. Gateway job status page currently says 

> [...]
Thu Dec 06 11:21:35 PST 2018 > INPUTSTAGING : SUCCESS : NGBW-JOB-RELION_2D_CLASS_COMET-2EAFA1772CC148C382E2A222890D741F : Input files staged successfully 
> Thu Dec 06 11:21:36 PST 2018 > SUBMITTING : ERROR : NGBW-JOB-RELION_2D_CLASS_COMET-2EAFA1772CC148C382E2A222890D741F : java.lang.Exception: Error submitting job: /projects/cosmic2/gateway/workspace/NGBW-JOB-RELION_2D_CLASS_COMET-2EAFA1772CC148C382E2A222890D741F . Traceback (most recent call last): File "/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/comet_relion_submit.py", line 349, in <module> relion_command,outdir,runhours,nodes,numiters,worksubdir=prepareRelionRun(args['commandline']) File "/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/comet_relion_submit.py", line 50, in prepareRelionRun rlno1=open(starfilename,'r') IOError: [Errno 2] No such file or directory: 'data/2d'

**Comment by monaw** [comment]
Ok, I've updated TasksInitiate.java and SSHExecProcessWorker.java and now:

1. Email says 

> Error submitting job : [Errno 2] No such file or directory: 'data/2d'

2. Gateway says 

> [...]
Thu Dec 06 17:04:24 PST 2018 > INPUTSTAGING : SUCCESS : NGBW-JOB-RELION_2D_CLASS_COMET-A636BDE19E6D4CBF900E855B20501DB1 : Staging input files to COMET 
> Thu Dec 06 17:04:24 PST 2018 > INPUTSTAGING : SUCCESS : NGBW-JOB-RELION_2D_CLASS_COMET-A636BDE19E6D4CBF900E855B20501DB1 : Input files staged successfully 
> Thu Dec 06 17:04:26 PST 2018 > SUBMITTING : ERROR : NGBW-JOB-RELION_2D_CLASS_COMET-A636BDE19E6D4CBF900E855B20501DB1 : java.lang.Exception: Error submitting job : [Errno 2] No such file or directory: 'data/2d'
