### ISSUE TITLE
error submitting 3d classification cloned job

### ISSUE THREAD

**Issue by monaw** [cianfrocco-lab/COSMIC-CryoEM-Gateway#180]
when i submit a 3d classification cloned job, i see the following error in the gateway:

> Fri Apr 12 09:40:20 PDT 2019 > SUBMITTING : ERROR : NGBW-JOB-RELION_3D_CLASS_COMET-7FA9C7FA9D8C48CD9864A27C7A8AE3A3 : java.lang.Exception: Error submitting job: Traceback (most recent call last): File "/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/comet_relion_submit.py", line 770, in <module> relion_command,outdir,out_destination,runhours,nodes,numiters,worksubdir,partition,gpuextra1,gpuextra2,gpuextra3,mpi_to_use=prepareRelionRun(args) File "/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/comet_relion_submit.py", line 485, in prepareRelionRun os.makedirs('Class3D_cosmic') File "/share/apps/compute/python-2.7.14/lib/python2.7/os.py", line 157, in makedirs mkdir(name, mode) OSError: [Errno 17] File exists: 'Class3D_cosmic' 

FYI, the original task ran fine but the cloned one failed...

**Comment by mcianfrocco** [comment]
Is this related to #113 ?
