### ISSUE TITLE
Error: Transfer status page after Globus download of directory

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#71]
Just synced a directory from COSMIC2 to local machine using Globus - the Globus transfer worked but the 'Transfer status' page returned as an error once the task succeeded. As in, when the job was transferring ('ACTIVE' globus status), the transfer status was displayed properly, but once it was succeeded the gateway threw an error. 

This error persists on the Transfer Status page, as whenever I return there is the same error: 

![error_globus](https://user-images.githubusercontent.com/1464469/32034201-384b9b22-b9df-11e7-821b-ca8ff8ead8bf.png)

**Comment by mcianfrocco** [comment]
This error goes away after clicking on Data > Globus upload, and then it displays the transfer page again.


Should be noted that this is likely the way users will be downloading directories with Globus, so this will be the data exit strategy

**Comment by mcianfrocco** [comment]
For what it's worth, the Globus syncing is working fine going from COSMIC2 to local. It is just our gateway that has to recognize this type of data movement.

**Comment by monaw** [comment]
runtime error in all-gateway.log:
```
Nov 09 2017 11:37:05 [xec-16] ERROR - ceptionMappingInterceptor:42     | Parameter 'directory' is not a directory
java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
	at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:476)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:452)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:622)
	at edu.sdsc.globusauth.controller.Transfer2DataManager.saveDirectories(Transfer2DataManager.java:115)
	at edu.sdsc.globusauth.controller.Transfer2DataManager.setupDataItems(Transfer2DataManager.java:64)
	at edu.sdsc.globusauth.controller.ProfileManager.updateRecord(ProfileManager.java:168)
	at edu.sdsc.globusauth.action.TransferStatusAction.transfer_status(TransferStatusAction.java:135)
```

**Comment by monaw** [comment]
@mcianfrocco - THIS is the one that I just fixed and tested successfully; please confirm...

**Comment by mcianfrocco** [comment]
Worked! : )
