### ISSUE TITLE
Tasks not staging

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#84]
Issue for being able to stage and submit jobs: 

<img width="753" alt="error" src="https://user-images.githubusercontent.com/1464469/33511324-9add34ac-d6e6-11e7-838a-98dfb5be9449.png">

Are you having any issues, @monaw ?

**Comment by monaw** [comment]
Just checked and saving task works for me.

Ok, I see the following runtime error in the logs:

```
Dec 01 2017 19:30:44 [xec-23] DEBUG -                FolderItem:472    |        MONA : pushInsertOps 2
 Dec 01 2017 19:30:44 [xec-23] ERROR -                       Row:83     | com.   mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot  add or update a child row: a foreign key constraint fails (`cosmic2_sg`.        `task_input_source_documents`, CONSTRAINT `task_input_source_documents_ibfk_2`  FOREIGN KEY (`SOURCE_DOCUMENT_ID`) REFERENCES `source_documents`                (`SOURCE_DOCUMENT_ID`))
 Dec 01 2017 19:30:44 [xec-23] DEBUG -               NgbwSupport:1029   |        michaelc - Error saving and running current task: com.mysql.jdbc.exceptions.    jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child  row: a foreign key constraint fails (`cosmic2_sg`.                              `task_input_source_documents`, CONSTRAINT `task_input_source_documents_ibfk_2`  FOREIGN KEY (`SOURCE_DOCUMENT_ID`) REFERENCES `source_documents`                (`SOURCE_DOCUMENT_ID`))
 com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException:     Cannot add or update a child row: a foreign key constraint fails (`cosmic2_sg`. `task_input_source_documents`, CONSTRAINT `task_input_source_documents_ibfk_2`  FOREIGN KEY (`SOURCE_DOCUMENT_ID`) REFERENCES `source_documents`                (`SOURCE_DOCUMENT_ID`))
     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     at sun.reflect.NativeConstructorAccessorImpl.                               newInstance(NativeConstructorAccessorImpl.java:62)
     at sun.reflect.DelegatingConstructorAccessorImpl.                           newInstance(DelegatingConstructorAccessorImpl.java:45)
     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
     at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
     at com.mysql.jdbc.Util.getInstance(Util.java:386)
     at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4120)
     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4052)
     at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2503)
     at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2664)
     at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2815)
     at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java: 2155)
     at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:   2458)
     at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:   2375)
     at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:   2359)
     at net.sf.log4jdbc.PreparedStatementSpy.executeUpdate(PreparedStatementSpy. java:1022)
     at org.ngbw.sdk.database.AutoGenKeyInsertOp.execute(AutoGenKeyInsertOp.     java:93)
     at org.ngbw.sdk.database.Row.executeOps(Row.java:276)
     at org.ngbw.sdk.database.Row.save(Row.java:180)
     at org.ngbw.sdk.database.TaskInputSourceDocument.                           save(TaskInputSourceDocument.java:326)
     at org.ngbw.sdk.database.Task$AddInputOp.execute(Task.java:187)
```
I will try to take a look at this closer before leaving next wednesday morning...

**Comment by monaw** [comment]
@mcianfrocco - please confirm you got that error after clicking on the "Save and Run Task"?  If yes, please try "Save Task" and let me know what happens, thanks!

**Comment by monaw** [comment]
Never mind, I am able to reproduce this error now...working on it...

**Comment by monaw** [comment]
Original task_input_source_documents table:

```
MySQL [cosmic2_sg]> describe task_input_source_documents;
+--------------------+--------------+------+-----+---------+----------------+
| Field              | Type         | Null | Key | Default | Extra          |
+--------------------+--------------+------+-----+---------+----------------+
| INPUT_DOCUMENT_ID  | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| INPUT_ID           | bigint(20)   | NO   | MUL | NULL    |                |
| SOURCE_DOCUMENT_ID | bigint(20)   | NO   | MUL | NULL    |                |
| DATAFORMAT         | varchar(255) | NO   |     | NULL    |                |
| DATATYPE           | varchar(255) | NO   |     | NULL    |                |
| ENTITYTYPE         | varchar(255) | NO   |     | NULL    |                |
| NAME               | varchar(255) | YES  |     | NULL    |                |
| VALIDATED          | bit(1)       | NO   |     | b'0'    |                |
+--------------------+--------------+------+-----+---------+----------------+
8 rows in set (0.00 sec)

```

Changed table to allow null in source_document_id column:

```
MySQL [cosmic2_sg]> alter table task_input_source_documents modify column SOURCE_DOCUMENT_ID bigint(20);
Query OK, 0 rows affected (0.15 sec)
Records: 0  Duplicates: 0  Warnings: 0

MySQL [cosmic2_sg]> describe task_input_source_documents;
+--------------------+--------------+------+-----+---------+----------------+
| Field              | Type         | Null | Key | Default | Extra          |
+--------------------+--------------+------+-----+---------+----------------+
| INPUT_DOCUMENT_ID  | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| INPUT_ID           | bigint(20)   | NO   | MUL | NULL    |                |
| SOURCE_DOCUMENT_ID | bigint(20)   | YES  | MUL | NULL    |                |
| DATAFORMAT         | varchar(255) | NO   |     | NULL    |                |
| DATATYPE           | varchar(255) | NO   |     | NULL    |                |
| ENTITYTYPE         | varchar(255) | NO   |     | NULL    |                |
| NAME               | varchar(255) | YES  |     | NULL    |                |
| VALIDATED          | bit(1)       | NO   |     | b'0'    |                |
+--------------------+--------------+------+-----+---------+----------------+
8 rows in set (0.00 sec)

```

**Comment by mcianfrocco** [comment]
Hi Mona - did you test this yet? I have tried to stage other tasks and I keep getting the same error.

**Comment by monaw** [comment]
Yup, still working on it...waiting for some help on the database problem...

**Comment by mcianfrocco** [comment]
Thanks Mona : )

**Comment by monaw** [comment]
@mcianfrocco - ok finally fixed!  Please test, thanks!

**Comment by mcianfrocco** [comment]
Yay - fixed!
