### ISSUE TITLE
 Error retrieving output results after job completes

### ISSUE THREAD

**Issue by mcianfrocco** [cianfrocco-lab/COSMIC-CryoEM-Gateway#88]
This error appears to be due to the transfer of the output.tar.gz file. 

For this error, I want to remove the step of the gateway 'ingesting' the output.tar.gz file, instead just letting the cluster batch script copy the data back into the user's Globus directory. That way users can just sync back their output results.

So - can we find out where this error is coming from and then remove the handling of output.tar.gz? 

```
Thu Dec 07 18:41:11 PST 2017 > LOAD_RESULTS : SUCCESS : NGBW-JOB-RELION_2D_CLASS_COMET-C9713F000F314C4FA9B27D34A963A47B : Trying to transfer results. 
Thu Dec 07 18:41:16 PST 2017 > LOAD_RESULTS : ERROR : NGBW-JOB-RELION_2D_CLASS_COMET-C9713F000F314C4FA9B27D34A963A47B : Error retrieving results for NGBW-JOB-RELION_2D_CLASS_COMET-C9713F000F314C4FA9B27D34A963A47B. Up to 40 automatic retries will be made. 
```

**Comment by mcianfrocco** [comment]
FWIW the stdout and stderr are ingested correctly as 'output files' from the job, which is all we need from the job within the job status output page.

**Comment by mcianfrocco** [comment]
Debug information from the loadResults.log: 

```
Jan 29 2018 19:48:21 [read-6] DEBUG -               LoadResults:308   [task=416, job=NGBW-JOB-RELION_2D_CLASS_COMET-C09CC833070A40838B66CE14D319DD24] | LoadResults took 12 seconds, or 0 minutes.
Jan 29 2018 20:07:48 [main  ] DEBUG -               LoadResults:211    | Found 1 tasks to process: NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2-TERMINATED-, 
Jan 29 2018 20:07:58 [read-7] DEBUG -               LoadResults:277   [task=417, job=NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2] | Loading Results for NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2
Jan 29 2018 20:07:58 [read-7] DEBUG -           SFTPFileHandler:79    [task=417, job=NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2] | Configured host: comet
Jan 29 2018 20:07:58 [read-7] DEBUG -         BaseProcessWorker:459   [task=417, job=NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2] | Making sure job's working dir /projects/cosmic2/gateway/workspace/NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2/ exists.
Jan 29 2018 20:07:59 [read-7] DEBUG -                 JobCharge:233   [task=417, job=NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2] | Trying to read: /projects/cosmic2/gateway/workspace/NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2//start.txt
Jan 29 2018 20:07:59 [read-7] DEBUG -                 JobCharge:242   [task=417, job=NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2] | read 1517285078
Jan 29 2018 20:07:59 [read-7] DEBUG -                 JobCharge:233   [task=417, job=NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2] | Trying to read: /projects/cosmic2/gateway/workspace/NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2//done.txt
Jan 29 2018 20:08:00 [read-7] DEBUG -                 JobCharge:242   [task=417, job=NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2] | read 1517285077
Jan 29 2018 20:08:00 [read-7] DEBUG -                 JobCharge:220   [task=417, job=NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2] | end=1517285077 - start=1517285078 is -1 seconds.  Hours=-2.777777777777778E-4
Jan 29 2018 20:08:01 [read-7] DEBUG -                 JobCharge:171   [task=417, job=NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2] | cores=15, ChargeFactor=1.0, hour=-2.777777777777778E-4, product=-0.004166666666666667, rounds to =1
Jan 29 2018 20:08:01 [read-7] INFO  -         BaseProcessWorker:259   [task=417, job=NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2] | JC - calculated jobcharge of 1
Jan 29 2018 20:08:01 [read-7] DEBUG -         BaseProcessWorker:531   [task=417, job=NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2] | MAX_FILE_SIZE=0, MAX_DIR_SIZE=0
Jan 29 2018 20:08:02 [read-7] DEBUG -                FileColumn:211   [task=417, job=NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2] | MONA : entered FileColumn.setParamValue()
Jan 29 2018 20:08:02 [read-7] DEBUG -                FileColumn:212   [task=417, job=NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2] | MONA : m_isModified = true
Jan 29 2018 20:08:02 [read-7] DEBUG -                FileColumn:215   [task=417, job=NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2] | MONA : fileName = /projects/cosmic2/gateway/db_documents/9d/bd/9dbd1b35c33903d95a0213cc8b2924526e23f2d5.bin
Jan 29 2018 20:08:02 [read-7] DEBUG -                FileColumn:217   [task=417, job=NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2] | MONA : newFile = /projects/cosmic2/gateway/db_documents/9d/bd/9dbd1b35c33903d95a0213cc8b2924526e23f2d5.bin
Jan 29 2018 20:08:02 [read-7] DEBUG -                FileColumn:219   [task=417, job=NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2] | MONA : tempFile = /projects/cosmic2/gateway/db_documents/temp/temp-5697330486646451728.bin
Jan 29 2018 20:08:02 [read-7] DEBUG -                FileColumn:222   [task=417, job=NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2] | MONA : setParamValue 1
Jan 29 2018 20:08:02 [read-7] DEBUG -                FileColumn:233   [task=417, job=NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2] | MONA : setParamValue 3
Jan 29 2018 20:08:02 [read-7] DEBUG -                FileColumn:235   [task=417, job=NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2] | MONA : setParamValue 4
Jan 29 2018 20:08:08 [read-7] ERROR -               TaskMonitor:308   [task=417, job=NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2] | Error retrieving results for NGBW-JOB-RELION_2D_CLASS_COMET-9EF5DF43BE0044B8838A7D022AF969D2. Up to 40 automatic retries will be made.
com.trilead.ssh2.SFTPException: Failure (SSH_FX_FAILURE: An error occurred, but no specific error code exists to describe the failure.)
	at com.trilead.ssh2.SFTPv3Client.read(SFTPv3Client.java:1296)
	at org.ngbw.sdk.tool.SFTPInputStream.read(SFTPInputStream.java:110)
	at org.ngbw.sdk.database.FileColumn$FileValue.setValue(FileColumn.java:162)
	at org.ngbw.sdk.database.StreamColumn.setValue(StreamColumn.java:216)
	at org.ngbw.sdk.database.SourceDocumentRow.setData(SourceDocumentRow.java:219)
	at org.ngbw.sdk.database.SourceDocumentRow.<init>(SourceDocumentRow.java:109)
	at org.ngbw.sdk.database.TaskOutputSourceDocument.<init>(TaskOutputSourceDocument.java:104)
	at org.ngbw.sdk.tool.BaseProcessWorker.storeOutputFiles(BaseProcessWorker.java:409)
	at org.ngbw.sdk.tool.BaseProcessWorker.storeTaskResults(BaseProcessWorker.java:347)
	at org.ngbw.sdk.tool.BaseProcessWorker.readAndStore(BaseProcessWorker.java:285)
	at org.ngbw.sdk.tool.BaseProcessWorker.getResults(BaseProcessWorker.java:236)
	at org.ngbw.sdk.tool.TaskMonitor.getResults(TaskMonitor.java:244)
	at org.ngbw.utils.LoadResults$ProcessRunningTask.run(LoadResults.java:278)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by monaw** [comment]
need issue #93 resolved before continuing...

**Comment by monaw** [comment]
@mcianfrocco - I ran a job using betagaltest yesterday and its working directory is at /projects/cosmic2/gateway/workspace/NGBW-JOB-RELION_2D_CLASS_COMET-03305ED46E2D474093769638EC0BE596/.  I can't tell if the job ran successfully or not...it seems not. Mike, can you take a look and see?

**Comment by mcianfrocco** [comment]
Hi @monaw - I've confirmed this error is in the comet_relion_submit.py script - I will address this problem.

**Comment by mcianfrocco** [comment]
Hi @monaw - I've found the bug and it's in comet_relion_submit, I'll work on this.

**Comment by monaw** [comment]
@mcianfrocco - you've fixed the above issue right?

**Comment by mcianfrocco** [comment]
Oops - yes - should've close this !

**Comment by monaw** [comment]
this one is also not done yet...

**Comment by monaw** [comment]
Tech note:  in each tools' xml file, the "<Results>" tag specifies the files to retrieve from the server after job is completed.

**Comment by monaw** [comment]
@mcianfrocco - ok, I believe this is now working...at least with my simple testing...the task status now does not show a transfer error and instead shows successful completion:

![screen shot 2018-03-13 at 1 30 16 pm](https://user-images.githubusercontent.com/18472048/37372659-c2dab698-26d0-11e8-8544-66b0ef608258.png)

and the stdout and stderr are the 2 result files the user can view and download:

![screen shot 2018-03-13 at 2 31 28 pm](https://user-images.githubusercontent.com/18472048/37372569-618f31b6-26d0-11e8-934c-4d033bf8049b.png)

By the way, during the job run, the task detail page contains a link to list, view & download the intermediate files:

![screen shot 2018-03-13 at 2 19 25 pm](https://user-images.githubusercontent.com/18472048/37372693-f010ca3a-26d0-11e8-8867-282dfca64e58.png)

when you click on the "Intermediate Results List" link, you will see:

![screen shot 2018-03-13 at 2 19 06 pm](https://user-images.githubusercontent.com/18472048/37372740-1915eee2-26d1-11e8-900e-9cce4ebdf669.png)

**Comment by monaw** [comment]
@mcianfrocco - by the way, my simple Relion 2D run using the betagaltest data seemed to have failed.  Can you tell what went wrong?  The task directory is at /projects/cosmic2/gateway/workspace/ARCHIVE/NGBW-JOB-RELION_2D_CLASS_COMET-731FACF9C9634BB8A0203341C4838BF3/

So one "issue" is that the gateway is getting the successful completion signal when it should receive an error instead; do you know how this should be handled in the backend script?

**Comment by mcianfrocco** [comment]
Hi Mona - this output transfer worked for me! My job ran successfully and the results were moved back into the correct Globus download folder : ) 

Regarding your error - i will look into this now.

**Comment by monaw** [comment]
yea, hooray!  thanks Mike!

**Comment by monaw** [comment]
@mcianfrocco - can you test both of the 3D Relion tools again and view the output listing page to be sure they looks right?  no duplicate or missing output...

here is how the 2D tool output page listing look:

![screen shot 2018-03-15 at 8 53 06 pm](https://user-images.githubusercontent.com/18472048/37503010-26f8bac6-2893-11e8-97a4-9c4fa6a87511.png)

**Comment by mcianfrocco** [comment]
Yes - I will check the 3D tools again and will report back by Monday.

**Comment by mcianfrocco** [comment]
Hi @monaw - I got an error with 3D classification: 

Tue Mar 20 10:21:06 PDT 2018 > INPUTSTAGING : ERROR : NGBW-JOB-RELION_3D_CLASS_COMET-C68AABE5701447C5A8294EF126A52101 : java.lang.NullPointerException 

Perhaps it's related to the 3D model specification?

**Comment by monaw** [comment]
@mcianfrocco - how about the 3d refinement?

can you give me a small dataset with map file so i can test the 3d classification?  also what's the parameters i should use for my testing:

![screen shot 2018-03-26 at 10 06 18 am](https://user-images.githubusercontent.com/18472048/37921032-7a2409d8-30dd-11e8-8e48-c9417d4f69ad.png)

**Comment by mcianfrocco** [comment]
Hi @monaw - I'll send an email with a download link and more information about the data. 

For the parameters: 

Diamter=200
Angpix=2 
Refmap=(file that I send to you)
Symmetry = C1
Initial low pass = 60 
Number of classes 3 
Angular intervals = 7.5
Pixel search = 5 
Pixel step size = 1

Mike

**Comment by monaw** [comment]
@mcianfrocco - thanks!  i see there are 2 star files (shiny_2sets_cosmic_binned.star and shiny_2sets_cosmic.star) on the top-level, which one should i use for testing 3d classification?

**Comment by mcianfrocco** [comment]
Hi Mona, 

Use shiny_2sets_cosmic_binned.star

**Comment by monaw** [comment]
tech note - Mike's 3d classification "java.lang.NullPointerException" error is due to the problem that the task_input_source_documents table's source_document_id column is NULL for the ref (reference) parameter which is a file (UserDataItem)...still need to figure out why it is NULL...

**Comment by monaw** [comment]
@mcianfrocco - just a reminder about this issue that hopefully you can fix?

**Comment by mcianfrocco** [comment]
Yes - sorry. On it!

**Comment by monaw** [comment]
Hi @mcianfrocco - ok, I've added this parameter to 3D classification with same default value and parameter name; see attached image.  I presume 3D refinement doesn't need this parameter?
Please test and let me know how it goes.  Thanks.

**Comment by mcianfrocco** [comment]
I @monaw - I just got a Globus error when trying up to upload data to test this. Think it's related to the server being down?
